<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-CJFGN1F" failures="1" tests="1" name="Login Test with InValid Inputs" time="39.304" errors="0" timestamp="2022-08-10T16:28:43 IST">
  <testcase classname="ciraLogin.Login" name="InValidInputLoginTest" time="5.813">
    <failure type="java.lang.AssertionError" message="expected [https://sandbox.ciranet.com/v2/managementportal/user/login] but found [https://sandbox.ciranet.com/v2/managementportal/home]">
      <![CDATA[java.lang.AssertionError: expected [https://sandbox.ciranet.com/v2/managementportal/user/login] but found [https://sandbox.ciranet.com/v2/managementportal/home]
at ciraLogin.Login.InValidInputLoginTest(Login.java:85)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- InValidInputLoginTest -->
  <testcase classname="ciraLogin.Login" name="LoginWithEmptyField" time="0.0">
    <ignored/>
  </testcase> <!-- LoginWithEmptyField -->
  <testcase classname="ciraLogin.Login" name="ValidInputLoginTest" time="0.0">
    <ignored/>
  </testcase> <!-- ValidInputLoginTest -->
  <testcase classname="ciraLogin.Login" name="ShowPasswordFunctionality" time="0.0">
    <ignored/>
  </testcase> <!-- ShowPasswordFunctionality -->
</testsuite> <!-- Login Test with InValid Inputs -->
